
version: '3'
services:
    db:
        image: mongo
    backend:
        image: node-api
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        image: react-nginx
        ports:
            - "8080:8080"
        depends_on:
            - backend